/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.sachController;
import data.excelFile;
import javax.swing.JOptionPane;
import models.Sach;

/**
 *
 * @author myPC
 */
public class nhapExcelFrame extends javax.swing.JFrame {
    excelFile exCTL = new excelFile();
    sachController tcCTL = new sachController();
    /**
     * Creates new form nhapExcelFrame
     */
    public nhapExcelFrame() {
        initComponents();
        setTitle("Nhập File Excel");
    }
    public void nhapExcelFunc(){
        exCTL.importExcel(imporTable);
        
    }
    //Ham load data tu bang len CSDL
    public void updateToDB(){
        //tcCTL.deleteAllTapChi();
        Sach tc = new Sach();
        try {
            for (int row = 0; row < imporTable.getRowCount(); row++) {
                float slf = Float.parseFloat((String) imporTable.getValueAt(row, 2));
                int sl = (int)slf;
                float gTf = Float.parseFloat((String) imporTable.getValueAt(row, 6));
                int gT = (int)gTf;
                
                tc.setMaTc((String) imporTable.getValueAt(row, 0));
                tc.setTenTc((String) imporTable.getValueAt(row, 1));
                tc.setSoLuong(sl);
                tc.setNxb((String) imporTable.getValueAt(row, 3));
                tc.setNgayXb((String) imporTable.getValueAt(row, 4));
                tc.setLoai((String) imporTable.getValueAt(row, 5));
                tc.setGiaTien(gT);
                
                tcCTL.insertTapChi(tc);
            }
            JOptionPane.showMessageDialog(rootPane, "Đã tải dữ liệu lên thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Kiểm tra lại dữ liệu!","Lỗi",0);
            System.err.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        imporTable = new javax.swing.JTable();
        chonBTN = new javax.swing.JButton();
        uploadBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        imporTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Số lượng", "NXB", "Ngày XB", "Thể loại", "Giá tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(imporTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(7, 7, 7))
        );

        chonBTN.setText("Chọn");
        chonBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonBTNActionPerformed(evt);
            }
        });

        uploadBTN.setText("Tải lên");
        uploadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(uploadBTN)
                .addGap(18, 18, 18)
                .addComponent(chonBTN)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chonBTN)
                    .addComponent(uploadBTN))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chonBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonBTNActionPerformed
        // TODO add your handling code here:
        nhapExcelFunc();
    }//GEN-LAST:event_chonBTNActionPerformed

    private void uploadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBTNActionPerformed
        // TODO add your handling code here:
        updateToDB();
    }//GEN-LAST:event_uploadBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nhapExcelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nhapExcelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nhapExcelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nhapExcelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nhapExcelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chonBTN;
    private javax.swing.JTable imporTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton uploadBTN;
    // End of variables declaration//GEN-END:variables
}
