/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.NhanVienDao;
import JdbcConnection.JdbcHelper;
import Utils.Auth;
import Validator.Validator;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.NhanVien;

/**
 *
 * @author Thinkpad
 */
public class doiMKDialog extends javax.swing.JDialog {
  
  NhanVienDao nvDAO;
  JdbcHelper connect;
  
  /**
   * Creates new form themDVDialog
   */
  public doiMKDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    customUI();
    initComponents();
    init();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
   * Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel2 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    txtXacNhan = new javax.swing.JTextField();
    txtMKmoi = new javax.swing.JTextField();
    txtMKcu = new javax.swing.JTextField();
    txtTaiKhoan = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    btnXacNhan = new javax.swing.JButton();
    btnHuy = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setUndecorated(true);

    jPanel2.setBackground(new java.awt.Color(241, 255, 246));
    jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 3, true));

    jPanel1.setBackground(new java.awt.Color(241, 255, 246));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtXacNhan.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    txtXacNhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    txtXacNhan.setOpaque(false);
    jPanel1.add(txtXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 230, -1));

    txtMKmoi.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    txtMKmoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    txtMKmoi.setOpaque(false);
    jPanel1.add(txtMKmoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 230, -1));

    txtMKcu.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    txtMKcu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    txtMKcu.setOpaque(false);
    jPanel1.add(txtMKcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 230, -1));

    txtTaiKhoan.setEditable(false);
    txtTaiKhoan.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    txtTaiKhoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    txtTaiKhoan.setOpaque(false);
    jPanel1.add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 230, -1));

    jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel1.setText("Tên tài khoản:");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

    jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel2.setText("Mật khẩu cũ:");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

    jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel3.setText("Mật khẩu mới;");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

    jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel4.setText("Xác nhận mật khẩu:");
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

    btnXacNhan.setBackground(new java.awt.Color(0, 255, 255));
    btnXacNhan.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    btnXacNhan.setText("Xác nhận");
    btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnXacNhanActionPerformed(evt);
      }
    });
    jPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

    btnHuy.setBackground(new java.awt.Color(0, 255, 255));
    btnHuy.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    btnHuy.setText("Huỷ");
    btnHuy.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHuyActionPerformed(evt);
      }
    });
    jPanel1.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
    // TODO add your handling code here:
    setVisible(false);
  }//GEN-LAST:event_btnHuyActionPerformed

  private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
    // TODO add your handling code here:
    doiMK();
  }//GEN-LAST:event_btnXacNhanActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(doiMKDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(doiMKDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(doiMKDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(doiMKDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        doiMKDialog dialog = new doiMKDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnHuy;
  private javax.swing.JButton btnXacNhan;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JTextField txtMKcu;
  private javax.swing.JTextField txtMKmoi;
  private javax.swing.JTextField txtTaiKhoan;
  private javax.swing.JTextField txtXacNhan;
  // End of variables declaration//GEN-END:variables
  void customUI() {
    //custom UI
    try {
      for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  void init() {
    this.setLocationRelativeTo(null);
    txtTaiKhoan.setText(Auth.user.getMaNV());
  }
  
  StringBuilder validator() {
    StringBuilder sb = new StringBuilder();
    Validator.checkEmpty(txtMKcu, sb, "Hãy nhập mật khẩu cũ");
    Validator.checkEmpty(txtMKmoi, sb, "Hãy nhập mật khẩu mới");
    Validator.checkEmpty(txtXacNhan, sb, "Hãy xác nhận lại mật khẩu");
    return sb;
  }
  
  void doiMK() {
    if(validator().length() > 0) {
      JOptionPane.showMessageDialog(this, validator() + "Đổi mật khẩu thất bại !", "Lỗi", HEIGHT);
      return;
    }
    if(!txtMKmoi.getText().equals(txtXacNhan.getText())) {
      JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu lỗi !", "Lỗi", HEIGHT);
      txtXacNhan.requestFocus();
      return;
    }
    connect = new JdbcHelper();
    nvDAO = new NhanVienDao();
    NhanVien nv = nvDAO.findByMaNV(txtTaiKhoan.getText(), connect);
    if(!nv.getMatKhau().equals(txtMKcu.getText())) {
      JOptionPane.showMessageDialog(this, "Mật khẩu cũ không đúng !", "Lỗi", HEIGHT);
      return;
    }
    if(nvDAO.updateNV(txtTaiKhoan.getText(), txtMKmoi.getText(), connect) == 1) {
      JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công !");
      Auth.user.setMatKhau(txtMKmoi.getText());
      this.setVisible(false);
    } else {
      JOptionPane.showMessageDialog(this, "Đổi mật khẩu thất bại !", "Lỗi", HEIGHT);
    }
  }
}
