/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.ChiTietHoaDonDAO;
import Dao.DichVuDAO;
import Dao.SanPhamDAO;
import JdbcConnection.JdbcHelper;
import static View.TrangChuFrame.maHD;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.HoaDonChiTiet;

/**
 *
 * @author Thinkpad
 */
public class HDCTDialog extends javax.swing.JDialog {

  JdbcHelper connect;
  ArrayList<HoaDonChiTiet> list;
  ChiTietHoaDonDAO cthdDAO;
  DichVuDAO dvDAO;
  SanPhamDAO spDAO;

  /**
   * Creates new form themDVDialog
   */
  public HDCTDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    customUI();
    initComponents();
    init();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
   * Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    jScrollPane12 = new javax.swing.JScrollPane();
    tblCTHD = new javax.swing.JTable();
    btnOK = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setUndecorated(true);

    jPanel2.setBackground(new java.awt.Color(241, 255, 246));
    jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 3, true));

    jScrollPane12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));

    tblCTHD.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    tblCTHD.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Tên giao dịch", "Số lượng", "Giá"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tblCTHD.setFocusable(false);
    tblCTHD.setOpaque(false);
    tblCTHD.setRowHeight(25);
    tblCTHD.setRowMargin(3);
    tblCTHD.setSelectionBackground(new java.awt.Color(255, 153, 153));
    tblCTHD.setSelectionForeground(new java.awt.Color(255, 255, 255));
    tblCTHD.setShowVerticalLines(false);
    tblCTHD.getTableHeader().setReorderingAllowed(false);
    jScrollPane12.setViewportView(tblCTHD);
    JTableHeader tableHeaderCTHD = tblCTHD.getTableHeader();     
    tableHeaderCTHD.setFont(new java.awt.Font("Dialog", 0, 17));
    tableHeaderCTHD.setBackground(new Color(0,147,223));     
    tableHeaderCTHD.setOpaque(false);
    tableHeaderCTHD.setForeground(Color.white);

    btnOK.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    btnOK.setText("OK");
    btnOK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnOKActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btnOK)))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnOK)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
    // TODO add your handling code here:
    setVisible(false);
  }//GEN-LAST:event_btnOKActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(HDCTDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(HDCTDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(HDCTDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(HDCTDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        HDCTDialog dialog = new HDCTDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnOK;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane12;
  private javax.swing.JTable tblCTHD;
  // End of variables declaration//GEN-END:variables
  void customUI() {
    //custom UI
    try {
      for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  void init() {
    this.setLocationRelativeTo(null);
    //ket noi csdl
    connect = new JdbcHelper();
    fillTable();
  }
  
  void fillTable() {
    cthdDAO = new ChiTietHoaDonDAO();
    dvDAO = new DichVuDAO();
    spDAO = new SanPhamDAO();
    list = cthdDAO.getHDCT(connect, maHD);
    DefaultTableModel model = (DefaultTableModel) tblCTHD.getModel();
    model.setRowCount(0);
    for(HoaDonChiTiet hdct : list) {
      String loaiHD= "";
      if(hdct.getMaSP()==null) {
        try {
          loaiHD = dvDAO.findByMaDV(hdct.getMaDV(), connect).getTenDV();
        } catch (Exception e) {
          loaiHD = "DV đã bị xoá";
        }        
      } else {
        try {
          loaiHD = spDAO.findByMaSP(hdct.getMaSP(), connect).getTenSP();
        } catch (Exception e) {
          loaiHD = "SP đã bị xoá";
        }
      }
      model.addRow(new Object[]{
        loaiHD, hdct.getSoLuongMua(), hdct.getGia()
      });
    }
  }
}
