/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.SanPhamDAO;
import JdbcConnection.JdbcHelper;
import Utils.DateHelper;
import Validator.Validator;
import static View.TrangChuFrame.dsSP;
import static View.TrangChuFrame.tblSP;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.SanPham;

/**
 *
 * @author Thinkpad
 */
public class themSPDialog extends javax.swing.JDialog {

  SanPhamDAO spDAO;
  JdbcHelper connect;
  ArrayList<SanPham> listSP;

  /**
   * Creates new form themDVDialog
   */
  public themSPDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    customUI();
    initComponents();
    init();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
   * Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    txtGiaBan = new javax.swing.JTextField();
    txtSoLuong = new javax.swing.JTextField();
    txtTenSP = new javax.swing.JTextField();
    txtMaSP = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    btnXacNhan = new javax.swing.JButton();
    btnHuy = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();
    txtGiaNhap = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    cboNgay = new javax.swing.JComboBox<>();
    cboThang = new javax.swing.JComboBox<>();
    cboNam = new javax.swing.JComboBox<>();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtGhiChu = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setUndecorated(true);

    jPanel2.setBackground(new java.awt.Color(241, 255, 246));
    jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 3, true));

    jPanel1.setBackground(new java.awt.Color(241, 255, 246));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtGiaBan.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    txtGiaBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    txtGiaBan.setOpaque(false);
    jPanel1.add(txtGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 230, -1));

    txtSoLuong.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    txtSoLuong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    txtSoLuong.setOpaque(false);
    jPanel1.add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 230, -1));

    txtTenSP.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    txtTenSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    txtTenSP.setOpaque(false);
    jPanel1.add(txtTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 230, -1));

    txtMaSP.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    txtMaSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    txtMaSP.setOpaque(false);
    txtMaSP.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtMaSPKeyReleased(evt);
      }
    });
    jPanel1.add(txtMaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 230, -1));

    jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel1.setText("Mã sản phẩm:");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

    jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel2.setText("Tên sản phẩm:");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

    jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel3.setText("Số lượng:");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

    jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel4.setText("Ngày nhập kho:");
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

    jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel5.setText("Ghi chú:");
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

    btnXacNhan.setBackground(new java.awt.Color(0, 255, 255));
    btnXacNhan.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    btnXacNhan.setText("Xác nhận");
    btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnXacNhanActionPerformed(evt);
      }
    });
    jPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

    btnHuy.setBackground(new java.awt.Color(0, 255, 255));
    btnHuy.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    btnHuy.setText("Huỷ");
    btnHuy.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHuyActionPerformed(evt);
      }
    });
    jPanel1.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 90, -1));

    jLabel6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel6.setText("Giá nhập :");
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

    txtGiaNhap.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    txtGiaNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    txtGiaNhap.setOpaque(false);
    jPanel1.add(txtGiaNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 230, -1));

    jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel7.setText("Giá bán :");
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

    cboNgay.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    cboNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
    cboNgay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    cboNgay.setOpaque(false);
    jPanel1.add(cboNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 60, -1));

    cboThang.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    cboThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
    cboThang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    cboThang.setOpaque(false);
    jPanel1.add(cboThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 60, -1));

    cboNam.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    cboNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
    cboNam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    cboNam.setOpaque(false);
    jPanel1.add(cboNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

    txtGhiChu.setColumns(20);
    txtGhiChu.setRows(5);
    jScrollPane1.setViewportView(txtGhiChu);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 240, 80));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
    // TODO add your handling code here:
    setVisible(false);
  }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
      // TODO add your handling code here:
      if (checkSP()) {
        themSP();
      } else {
        congDon();
      }
    }//GEN-LAST:event_btnXacNhanActionPerformed

  private void txtMaSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaSPKeyReleased
    // TODO add your handling code here:
    if(checkSP()) {
      resetForm();
    }
  }//GEN-LAST:event_txtMaSPKeyReleased

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(themSPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(themSPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(themSPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(themSPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        themSPDialog dialog = new themSPDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnHuy;
  private javax.swing.JButton btnXacNhan;
  private javax.swing.JComboBox<String> cboNam;
  private javax.swing.JComboBox<String> cboNgay;
  private javax.swing.JComboBox<String> cboThang;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea txtGhiChu;
  private javax.swing.JTextField txtGiaBan;
  private javax.swing.JTextField txtGiaNhap;
  private javax.swing.JTextField txtMaSP;
  private javax.swing.JTextField txtSoLuong;
  private javax.swing.JTextField txtTenSP;
  // End of variables declaration//GEN-END:variables
  void customUI() {
    //custom UI
    try {
      for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  void init() {
    this.setLocationRelativeTo(null);
    fillcomboboxDate();
  }

  StringBuilder validator() {
    StringBuilder sb = new StringBuilder();
    Validator.checkEmpty(txtMaSP, sb, "Mã Sản Phẩm không được để trống !");
    Validator.checkEmpty(txtTenSP, sb, "Tên Sản Phẩm không được để trống !");
    Validator.CheckNumber(txtSoLuong, sb, "Số Lượng không được để trống !");
    Validator.CheckNumber(txtGiaNhap, sb, "Giá Nhập không được để trống !");
    Validator.CheckNumber(txtGiaBan, sb, "Giá Bán không được để trông !");
    return sb;
  }

  void themSP() {
    if (validator().length() > 0) {
      JOptionPane.showMessageDialog(this, validator() + "Thêm thất bại !", "Lỗi", HEIGHT);
      return;
    }

    connect = new JdbcHelper();
    spDAO = new SanPhamDAO();
    SanPham sp = spDAO.findByMaSP(txtMaSP.getText(), connect);
    if (sp != null) {
      JOptionPane.showMessageDialog(this, "Sản Phẩm có mã " + txtMaSP.getText() + " đã tồn tại !", "Lỗi", HEIGHT);
      txtMaSP.requestFocus();
      return;
    }
    Date date;

    try {
      date = DateHelper.toDate(cboNgay.getSelectedItem() + "-" + cboThang.getSelectedItem() + "-" + cboNam.getSelectedItem(), "dd-MM-yyyy");
    } catch (Exception e) {
      return;
    }
    SanPham spNew = new SanPham();
    spNew.setMaSP(txtMaSP.getText());
    spNew.setTenSP(txtTenSP.getText());
    spNew.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
    spNew.setNgayNhapKho(date);
    spNew.setGiaBan(Double.valueOf(txtGiaBan.getText()));
    spNew.setGiaNhap(Double.valueOf(txtGiaNhap.getText()));
    spNew.setGhiChu(txtGhiChu.getText());
    if (spDAO.insertSP(spNew, connect) == 1) {
      JOptionPane.showMessageDialog(this, "Thêm thành công");
      fillTableSP();
      fillListSP();
      TrangChuFrame.txtTKNV.setText("");
      setVisible(false);
    } else {
      JOptionPane.showMessageDialog(this, "Thêm thất bại !", "Lỗi", HEIGHT);
    }
  }

  public void fillTableSP() {
    spDAO = new SanPhamDAO();
    listSP = spDAO.getSanPham(connect);
    DefaultTableModel model = (DefaultTableModel) tblSP.getModel();
    model.setRowCount(0);
    for (SanPham sp : listSP) {
      String ngaynhapkho = DateHelper.toString(sp.getNgayNhapKho(), "dd-MM-yyyy");
      model.addRow(new Object[]{
        sp.getMaSP(), sp.getTenSP(), sp.getSoLuong(), sp.getGiaNhap(), sp.getGiaBan(), sp.getGhiChu(), ngaynhapkho
      });
    }
  }

  void fillcomboboxDate() {
    String setDate[] = java.time.LocalDate.now().toString().split("-");
    cboNgay.setSelectedItem(setDate[2]);
    cboThang.setSelectedItem(setDate[1]);
    cboNam.setSelectedItem(setDate[0]);
  }

  void congDon() {
    if (validator().length() > 0) {
      JOptionPane.showMessageDialog(this, validator() + "Thêm thất bại !", "Lỗi", HEIGHT);
      return;
    }
    spDAO = new SanPhamDAO();
    connect = new JdbcHelper();
    int soLuong = Integer.parseInt(txtSoLuong.getText());
    if (spDAO.updateSLSP(txtMaSP.getText(), soLuong, connect) == 1) {
      JOptionPane.showMessageDialog(this, "Thêm thành công");
      fillTableSP();
      TrangChuFrame.txtTKNV.setText("");
      setVisible(false);
    } else {
      JOptionPane.showMessageDialog(this, "Thêm thất bại !", "Lỗi", HEIGHT);
    }
  }

  boolean checkSP() {
    String maSP = txtMaSP.getText();
    spDAO = new SanPhamDAO();
    connect = new JdbcHelper();
    SanPham sp = spDAO.findByMaSP(maSP, connect);
    if (sp != null) {
      fillForm(sp);
      setEditable(true);
      return false;
    } else {
      setEditable(false);
      return true;
    }
  }

  void fillForm(SanPham sp) {
    txtTenSP.setText(sp.getTenSP());
    txtSoLuong.requestFocus();
    txtGiaBan.setText(String.valueOf(sp.getGiaBan()));
    txtGiaNhap.setText(String.valueOf(sp.getGiaNhap()));
    String date[] = DateHelper.toString(sp.getNgayNhapKho(), "dd-MM-yyyy").split("-");
    cboNgay.setSelectedItem(date[0]);
    cboThang.setSelectedItem(date[1]);
    cboNam.setSelectedItem(date[2]);
    txtGhiChu.setText(sp.getGhiChu());
  }

  void setEditable(boolean check) {
    txtTenSP.setEditable(!check);
    txtGiaNhap.setEditable(!check);
    txtGiaBan.setEditable(!check);
    cboNgay.setEnabled(!check);
    cboThang.setEnabled(!check);
    cboNam.setEnabled(!check);
    txtGhiChu.setEditable(!check);
    btnXacNhan.setText("Thêm");
  }
  
  void resetForm() {
    txtTenSP.setText("");
    txtSoLuong.setText("");
    txtGiaBan.setText("");
    txtGiaNhap.setText("");
    fillcomboboxDate();
    txtGhiChu.setText("");
    btnXacNhan.setText("Xác nhận");
  }

  void fillListSP() {
    spDAO = new SanPhamDAO();
    listSP = spDAO.getSanPham(connect);
    DefaultListModel modelSP = new DefaultListModel<>();
    modelSP.removeAllElements();
    for (SanPham sp : listSP) {
      modelSP.addElement(sp.getTenSP());
    }
    dsSP.setModel(modelSP);
  }
}
