/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.DichVuDAO;
import Dao.LoaiHinhDAO;
import JdbcConnection.JdbcHelper;
import Validator.Validator;
import static View.TrangChuFrame.dsDV;
import static View.TrangChuFrame.tblDV;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.DichVu;
import model.LoaiHinhDichVu;

/**
 *
 * @author Thinkpad
 */
public class themDVDialog extends javax.swing.JDialog {

  JdbcHelper connect;
  LoaiHinhDAO lhDAO;
  DichVuDAO dvDAO;
  ArrayList<LoaiHinhDichVu> listLH;
  ArrayList<DichVu> listDV;

  /**
   * Creates new form themDVDialog
   */
  public themDVDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    customUI();
    initComponents();
    init();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
   * Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    txtTenDV = new javax.swing.JTextField();
    txtMaDV = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    btnXacNhan = new javax.swing.JButton();
    btnHuy = new javax.swing.JButton();
    cboMaLHDV = new javax.swing.JComboBox<>();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtGhiChuDV = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setUndecorated(true);

    jPanel2.setBackground(new java.awt.Color(241, 255, 246));
    jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 3, true));

    jPanel1.setBackground(new java.awt.Color(241, 255, 246));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtTenDV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    txtTenDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    txtTenDV.setOpaque(false);
    jPanel1.add(txtTenDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 230, -1));

    txtMaDV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    txtMaDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    txtMaDV.setOpaque(false);
    jPanel1.add(txtMaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 230, -1));

    jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel1.setText("Loại hình dịch vụ:");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

    jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel2.setText("Mã dịch vụ:");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

    jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel3.setText("Tên dịch vụ:");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

    jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    jLabel5.setText("Ghi chú:");
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

    btnXacNhan.setBackground(new java.awt.Color(0, 255, 255));
    btnXacNhan.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    btnXacNhan.setText("Xác nhận");
    btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnXacNhanActionPerformed(evt);
      }
    });
    jPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

    btnHuy.setBackground(new java.awt.Color(0, 255, 255));
    btnHuy.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    btnHuy.setText("Huỷ");
    btnHuy.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHuyActionPerformed(evt);
      }
    });
    jPanel1.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

    cboMaLHDV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    cboMaLHDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    cboMaLHDV.setOpaque(false);
    jPanel1.add(cboMaLHDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 230, 30));

    txtGhiChuDV.setColumns(20);
    txtGhiChuDV.setRows(5);
    txtGhiChuDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
    jScrollPane1.setViewportView(txtGhiChuDV);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 230, -1));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(69, 69, 69))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
    // TODO add your handling code here:
    setVisible(false);
  }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
      // TODO add your handling code here:
      themDV();
    }//GEN-LAST:event_btnXacNhanActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(themDVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(themDVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(themDVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(themDVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        themDVDialog dialog = new themDVDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnHuy;
  private javax.swing.JButton btnXacNhan;
  public static javax.swing.JComboBox<String> cboMaLHDV;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea txtGhiChuDV;
  private javax.swing.JTextField txtMaDV;
  private javax.swing.JTextField txtTenDV;
  // End of variables declaration//GEN-END:variables
  void customUI() {
    //custom UI
    try {
      for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  void init() {
    this.setLocationRelativeTo(null);
    //ket noi csdl
    connect = new JdbcHelper();
    //fillcombobox
    fillComboboxMaLH();
  }

  void fillComboboxMaLH() {
    lhDAO = new LoaiHinhDAO();
    listLH = lhDAO.getLoaiHinhDichVu(connect);
    for (LoaiHinhDichVu lh : listLH) {
      cboMaLHDV.addItem(lh.getTenLH() + " - " + lh.getMaLH());
    }
  }

  StringBuilder validatorDV() {
    StringBuilder sb = new StringBuilder();
    Validator.checkEmpty(txtMaDV, sb, "Mã Dịch Vụ không được để trống !");
    Validator.checkEmpty(txtTenDV, sb, "Tên Dịch Vụ không được để trống !");
    return sb;
  }

  void themDV() {
    if (validatorDV().length() > 0) {
      JOptionPane.showMessageDialog(this, validatorDV() + "Thêm thất bại !", "Lỗi", HEIGHT);
      return;
    }

    connect = new JdbcHelper();
    dvDAO = new DichVuDAO();
    DichVu sp = dvDAO.findByMaDV(txtMaDV.getText(), connect);
    if (sp != null) {
      JOptionPane.showMessageDialog(this, "Sản Phẩm có mã " + txtMaDV.getText() + " đã tồn tại !", "Lỗi", HEIGHT);
      txtMaDV.requestFocus();
      return;
    }

    DichVu dvNew = new DichVu();
    dvNew.setMaDV(txtMaDV.getText());
    dvNew.setTenDV(txtTenDV.getText());
    String MaLH[] = cboMaLHDV.getSelectedItem().toString().split("- ");
    dvNew.setMaLH(MaLH[1]);

    dvNew.setGhiChu(txtGhiChuDV.getText());
    if (dvDAO.insertDV(dvNew, connect) == 1) {
      JOptionPane.showMessageDialog(this, "Thêm thành công");
      fillTableDV();
      fillListDV();
      TrangChuFrame.txtTKNV.setText("");
      setVisible(false);
    } else {
      JOptionPane.showMessageDialog(this, "Thêm thất bại !", "Lỗi", HEIGHT);
    }
  }

  public void fillTableDV() {
    dvDAO = new DichVuDAO();
    listDV = dvDAO.getDichVu(connect);
    DefaultTableModel model = (DefaultTableModel) tblDV.getModel();
    model.setRowCount(0);
    for (DichVu dv : listDV) {
      model.addRow(new Object[]{
        dv.getMaLH(), dv.getMaDV(), dv.getTenDV(), dv.getGhiChu()
      });
    }
  }
  
  void fillListDV() {
    dvDAO = new DichVuDAO();
    lhDAO = new LoaiHinhDAO();
    dvDAO = new DichVuDAO();
    listLH = lhDAO.getLoaiHinhDichVu(connect);
    listDV = dvDAO.getDichVuByMaLH(connect, listLH.get(0).getMaLH());
    DefaultListModel modelDV = new DefaultListModel<>();
    modelDV.removeAllElements();
    for(DichVu dv : listDV) {
      modelDV.addElement(dv.getTenDV());
    }
    dsDV.setModel(modelDV);
  }
}
